<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-18T19:38:27 IST" name="Suite" finished-at="2024-03-18T19:38:31 IST" duration-ms="3432">
    <groups>
    </groups>
    <test started-at="2024-03-18T19:38:27 IST" name="Test" finished-at="2024-03-18T19:38:31 IST" duration-ms="3432">
      <class name="testcases.Getrecordbasedonthecustomerid">
        <test-method signature="getrecordbasedontheid()[pri:0, instance:testcases.Getrecordbasedonthecustomerid@6b927fb]" started-at="2024-03-18T19:38:27 IST" name="getrecordbasedontheid" finished-at="2024-03-18T19:38:30 IST" duration-ms="2566" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at testcases.Getrecordbasedonthecustomerid.getrecordbasedontheid(Getrecordbasedonthecustomerid.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getrecordbasedontheid -->
      </class> <!-- testcases.Getrecordbasedonthecustomerid -->
      <class name="testcases.deletecustomer">
        <test-method signature="deletethecustomers()[pri:0, instance:testcases.deletecustomer@1aa7ecca]" started-at="2024-03-18T19:38:30 IST" name="deletethecustomers" finished-at="2024-03-18T19:38:30 IST" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletethecustomers -->
      </class> <!-- testcases.deletecustomer -->
      <class name="testcases.Addcustomer">
        <test-method signature="addcustomer()[pri:0, instance:testcases.Addcustomer@9f116cc]" started-at="2024-03-18T19:38:30 IST" name="addcustomer" finished-at="2024-03-18T19:38:30 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addcustomer -->
      </class> <!-- testcases.Addcustomer -->
      <class name="testcases.GetAllTheCustomers_requestes">
        <test-method signature="getallthecustomers()[pri:0, instance:testcases.GetAllTheCustomers_requestes@59309333]" started-at="2024-03-18T19:38:30 IST" name="getallthecustomers" finished-at="2024-03-18T19:38:31 IST" duration-ms="521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getallthecustomers -->
      </class> <!-- testcases.GetAllTheCustomers_requestes -->
      <class name="testcases.GetAllTheCustomers">
        <test-method signature="getallthecustomers()[pri:0, instance:testcases.GetAllTheCustomers@12468a38]" started-at="2024-03-18T19:38:30 IST" name="getallthecustomers" finished-at="2024-03-18T19:38:30 IST" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getallthecustomers -->
      </class> <!-- testcases.GetAllTheCustomers -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
